version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    # volumes:
    #   - .mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    environment:
     - SPROCKETS_CACHE=/cache
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/sky_shift
    ports:
      - "3000:3000"
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8080:80